
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.adolfo.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVEOUT = 59;
  public static final int HEXADECIMAL = 91;
  public static final int DIVISION = 51;
  public static final int H1 = 16;
  public static final int TYPE = 25;
  public static final int COROUT = 53;
  public static final int ALERTF = 70;
  public static final int NAME = 27;
  public static final int DESCF = 63;
  public static final int INIT = 74;
  public static final int ALT = 34;
  public static final int BACKGROUND = 20;
  public static final int NOT = 47;
  public static final int THENWHILE = 82;
  public static final int REVERSEF = 66;
  public static final int THEN = 80;
  public static final int PRODUCTO = 50;
  public static final int HTML = 2;
  public static final int WIDTH = 32;
  public static final int BOOLEANO = 38;
  public static final int PROCESOS = 85;
  public static final int DOSP = 60;
  public static final int ALINGN = 24;
  public static final int TEXTAREA = 9;
  public static final int REDIRECT = 69;
  public static final int COMA = 56;
  public static final int HUNTIL = 79;
  public static final int ENTERO = 36;
  public static final int IGUAL = 42;
  public static final int CLASE = 30;
  public static final int LETPF = 64;
  public static final int WHILE = 81;
  public static final int IDCM = 26;
  public static final int CARALEF = 67;
  public static final int DECIMAL = 37;
  public static final int CHAR = 39;
  public static final int INPUT = 8;
  public static final int BOOLEANOS = 86;
  public static final int FONTSZ = 22;
  public static final int DIV = 12;
  public static final int NUMALEF = 68;
  public static final int GETID = 72;
  public static final int P = 17;
  public static final int ELSE = 77;
  public static final int LOAD = 61;
  public static final int CORIN = 52;
  public static final int MAQ = 44;
  public static final int PAROUT = 55;
  public static final int NUMDECIMAL = 89;
  public static final int LINK = 5;
  public static final int EOF = 0;
  public static final int REFERENCIA = 19;
  public static final int APOSTROFO = 84;
  public static final int SUMA = 48;
  public static final int BUTTON = 15;
  public static final int FONTFY = 23;
  public static final int CARACTER = 90;
  public static final int REPEAT = 78;
  public static final int SPAM = 7;
  public static final int SCRIPT = 18;
  public static final int SRC = 31;
  public static final int BODY = 6;
  public static final int TITLE = 4;
  public static final int COMILLA = 83;
  public static final int OR = 45;
  public static final int EXIT = 71;
  public static final int error = 1;
  public static final int RESTA = 49;
  public static final int IF = 76;
  public static final int PARIN = 54;
  public static final int ID = 87;
  public static final int COLOR = 21;
  public static final int HEAD = 3;
  public static final int END = 75;
  public static final int NUMENTERO = 88;
  public static final int IMG = 13;
  public static final int ASCF = 62;
  public static final int PUNTOCOMA = 57;
  public static final int HEIGHT = 33;
  public static final int BR = 14;
  public static final int LETIMF = 65;
  public static final int FILA = 29;
  public static final int GLOBAL = 41;
  public static final int LLAVEIN = 58;
  public static final int CADENA = 92;
  public static final int OPTION = 11;
  public static final int COLUMNA = 28;
  public static final int SELECTED = 10;
  public static final int INSERT = 73;
  public static final int STRING = 40;
  public static final int ONCLICK = 35;
  public static final int AND = 46;
  public static final int MEQ = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HTML",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECTED",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "H1",
  "P",
  "SCRIPT",
  "REFERENCIA",
  "BACKGROUND",
  "COLOR",
  "FONTSZ",
  "FONTFY",
  "ALINGN",
  "TYPE",
  "IDCM",
  "NAME",
  "COLUMNA",
  "FILA",
  "CLASE",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "CHAR",
  "STRING",
  "GLOBAL",
  "IGUAL",
  "MEQ",
  "MAQ",
  "OR",
  "AND",
  "NOT",
  "SUMA",
  "RESTA",
  "PRODUCTO",
  "DIVISION",
  "CORIN",
  "COROUT",
  "PARIN",
  "PAROUT",
  "COMA",
  "PUNTOCOMA",
  "LLAVEIN",
  "LLAVEOUT",
  "DOSP",
  "LOAD",
  "ASCF",
  "DESCF",
  "LETPF",
  "LETIMF",
  "REVERSEF",
  "CARALEF",
  "NUMALEF",
  "REDIRECT",
  "ALERTF",
  "EXIT",
  "GETID",
  "INSERT",
  "INIT",
  "END",
  "IF",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "THEN",
  "WHILE",
  "THENWHILE",
  "COMILLA",
  "APOSTROFO",
  "PROCESOS",
  "BOOLEANOS",
  "ID",
  "NUMENTERO",
  "NUMDECIMAL",
  "CARACTER",
  "HEXADECIMAL",
  "CADENA"
  };
}

